### ISSUE TITLE
Fail at start with dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.PulseAudio1': no such name

### ISSUE THREAD

**Issue by sgourichon** [nullEuro/apply-equalizer#3]
Some times, the script fails at start and outputs this:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.PulseAudio1': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./apply-equalizer.py", line 70, in <module>
    'org.PulseAudio1', '/org/pulseaudio/server_lookup1')\
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.PulseAudio1 was not provided by any .service files
```

Running the script again doesn't change anything.

Logging out and in, it then succeeds.

Perhaps a bug in pulseaudio's `module-dbus-protocol` ?

**Comment by nullEuro** [comment]
> Perhaps a bug in pulseaudio's `module-dbus-protocol` ?

Yes that seems to be the case. Instead of logging in and out you can restart pulseaudio: `pulseaudio -k` that solves the problem. I will commit a fix which does this automatically after 10 attempts to connect to Pulseaudio-DBus.
